"""Shared dataset feature schema and dimension names.

Used by both ``generate_dataset.py`` (to define the LeRobot dataset
features) and ``visualize_dataset.py`` (to label scalar dimensions in
Rerun).
"""

from .constants import IMAGE_SIZE

FEATURES = {
    "observation.images.overhead": {
        "dtype": "image",
        "shape": (IMAGE_SIZE, IMAGE_SIZE, 3),
        "names": ["height", "width", "channels"],
    },
    "observation.images.wrist": {
        "dtype": "image",
        "shape": (IMAGE_SIZE, IMAGE_SIZE, 3),
        "names": ["height", "width", "channels"],
    },
    "observation.state": {
        "dtype": "float32",
        "shape": (11,),
        "names": None,
    },
    "observation.state.ee.pos_quat_g": {
        "dtype": "float32",
        "shape": (8,),
        "names": None,
    },
    "observation.state.ee.pos_rot6d_g": {
        "dtype": "float32",
        "shape": (10,),
        "names": None,
    },
    "observation.state.ee.pos_quat_g_rel": {
        "dtype": "float32",
        "shape": (8,),
        "names": None,
    },
    "observation.state.ee.pos_rot6d_g_rel": {
        "dtype": "float32",
        "shape": (10,),
        "names": None,
    },
    "action.ee.pos_quat_g": {
        "dtype": "float32",
        "shape": (8,),
        "names": None,
    },
    "action.ee.pos_rot6d_g": {
        "dtype": "float32",
        "shape": (10,),
        "names": None,
    },
    "action.ee.pos_quat_g_rel": {
        "dtype": "float32",
        "shape": (8,),
        "names": None,
    },
    "action.ee.pos_rot6d_g_rel": {
        "dtype": "float32",
        "shape": (10,),
        "names": None,
    },
    "observation.target_bin_onehot": {
        "dtype": "float32",
        "shape": (3,),
        "names": None,
    },
    "observation.target_obj_onehot": {
        "dtype": "float32",
        "shape": (3,),
        "names": None,
    },
    "observation.keypoints_overhead": {
        "dtype": "float32",
        "shape": (14,),
        "names": None,
    },
    "observation.keypoints_wrist": {
        "dtype": "float32",
        "shape": (14,),
        "names": None,
    },
    "observation.target_obj_keypoints_overhead": {
        "dtype": "float32",
        "shape": (2,),
        "names": None,
    },
    "observation.target_bin_keypoints_overhead": {
        "dtype": "float32",
        "shape": (2,),
        "names": None,
    },
    "observation.phase_description": {
        "dtype": "string",
        "shape": (1,),
        "names": None,
    },
    "next.reward": {
        "dtype": "float32",
        "shape": (6,),
        "names": None,
    },
}

DIM_NAMES: dict[str, list[str]] = {
    "observation.state": [
        "ee_x",
        "ee_y",
        "ee_z",
        "gripper",
        "q0",
        "q1",
        "q2",
        "q3",
        "q4",
        "q5",
        "q6",
    ],
    "observation.state.ee.pos_quat_g": [
        "x",
        "y",
        "z",
        "qx",
        "qy",
        "qz",
        "qw",
        "gripper",
    ],
    "observation.state.ee.pos_rot6d_g": [
        "x",
        "y",
        "z",
        "r11",
        "r12",
        "r13",
        "r21",
        "r22",
        "r23",
        "gripper",
    ],
    "observation.state.ee.pos_quat_g_rel": [
        "x",
        "y",
        "z",
        "qx",
        "qy",
        "qz",
        "qw",
        "gripper",
    ],
    "observation.state.ee.pos_rot6d_g_rel": [
        "x",
        "y",
        "z",
        "r11",
        "r12",
        "r13",
        "r21",
        "r22",
        "r23",
        "gripper",
    ],
    "action.ee.pos_quat_g": ["x", "y", "z", "qx", "qy", "qz", "qw", "gripper"],
    "action.ee.pos_rot6d_g": [
        "x",
        "y",
        "z",
        "r11",
        "r12",
        "r13",
        "r21",
        "r22",
        "r23",
        "gripper",
    ],
    "action.ee.pos_quat_g_rel": ["x", "y", "z", "qx", "qy", "qz", "qw", "gripper"],
    "action.ee.pos_rot6d_g_rel": [
        "x",
        "y",
        "z",
        "r11",
        "r12",
        "r13",
        "r21",
        "r22",
        "r23",
        "gripper",
    ],
    "observation.target_bin_onehot": ["red", "green", "blue"],
    "observation.target_obj_onehot": ["red", "green", "blue"],
    "observation.keypoints_overhead": [
        "red_u",
        "red_v",
        "green_u",
        "green_v",
        "blue_u",
        "blue_v",
        "bin_red_u",
        "bin_red_v",
        "bin_green_u",
        "bin_green_v",
        "bin_blue_u",
        "bin_blue_v",
        "hand_u",
        "hand_v",
    ],
    "observation.keypoints_wrist": [
        "red_u",
        "red_v",
        "green_u",
        "green_v",
        "blue_u",
        "blue_v",
        "bin_red_u",
        "bin_red_v",
        "bin_green_u",
        "bin_green_v",
        "bin_blue_u",
        "bin_blue_v",
        "hand_u",
        "hand_v",
    ],
    "observation.target_obj_keypoints_overhead": ["u", "v"],
    "observation.target_bin_keypoints_overhead": ["u", "v"],
    "next.reward": [
        "total",
        "reach_obj",
        "pick_obj",
        "reach_target",
        "place_obj",
        "reach_home",
    ],
}
